image: ubuntu:latest
 
pipelines:
  default:
    - step:
        name: dev deployment
        deployment: test
        script:
          - apt-get update
          - apt-get install zip unzip -y
          - apt-get install openssh-client -y
          - apt-get install -y ca-certificates curl gnupg
          - mkdir -p /etc/apt/keyrings
          - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
          - NODE_MAJOR=18
          - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
          - apt-get update
          - apt-get install nodejs -y
          - npm install
          - CI=false npm run build
          - ls -lrt
          - zip -r "Jobportal-ui.zip" . -x "node_modules/*"
          - ls -lrt
          - chmod +x "Jobportal-ui.zip"
          - scp Jobportal-ui.zip jobportal@20.198.9.131:/home/jobportal/
          - ssh jobportal@20.198.9.131 "unzip -o /home/jobportal/Jobportal-ui.zip -d jobportal-ui"
          - ssh jobportal@20.198.9.131 "sh /home/jobportal/jobportal-ui/jobportal-ui-deploy.sh"